### ISSUE TITLE
Can't start new session

### ISSUE THREAD

**Issue by Cosolom** [allape/Java-IDEAPlugin-XFTP#1]
Hello. When I press "Start new session" button I get error
class com.jetbrains.plugins.remotesdk.console.RemoteConnectionSettingsForm$1 cannot be cast to class com.jetbrains.plugins.remotesdk.console.SshConfigConnector (com.jetbrains.plugins.remotesdk.console.RemoteConnectionSettingsForm$1 and com.jetbrains.plugins.remotesdk.console.SshConfigConnector are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @7ab0dca0)
What I doing wrong or what can be source of error? Should I do module configuration? https://prnt.sc/1uxh0wg

**Comment by allape** [comment]
What is the version of your ide? This error should be a bug...

**Comment by allape** [comment]
This error will be produced while there is no ssh config preset or choose the "Edit credentials..." in the connections popup. This bug will be fixed in the next version.

**Comment by Cosolom** [comment]
Thank you!! It's on PhpStorm 2021.2.2
I have ssh configrations in Tools/SSH Configurations. Should I configure something additional? Or need to wait for next release of plugin?

**Comment by allape** [comment]
> Thank you!! It's on PhpStorm 2021.2.2 I have ssh configrations in Tools/SSH Configurations. Should I configure something additional? Or need to wait for next release of plugin?

At v0.10.0, it should be ok if the ssh is configured. v0.10.1has been uploaded to marketplace, and waiting for approval. You can also download the zip from github release, [v0.10.1](https://github.com/allape/Java-IDEAPlugin-XFTP/releases/tag/v0.10.1)🙂

**Comment by Cosolom** [comment]
Thank you @allape ! New version is works. But I found why I can't see any available ssh connections. All my ssh configurations have enabled option "Visible only for this project". And when I switch off the checkbox then I can connect to a server. I hope this will help. Thank you for your module, now I can test it :)

**Comment by allape** [comment]
This should be a bug too, I'm gonna work on it in the next version 😂.
