### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by fangtaosong** [allape/Java-IDEAPlugin-XFTP#2]
hi，考虑过和右侧的remotehost合并吗
![image](https://user-images.githubusercontent.com/59201842/197191196-34aa1d95-cc61-4cb8-be97-b0373c1a2595.png)

**Comment by allape** [comment]
后续这个项目可能不会再维护了, 因为官方推出了类似的功能了;
比如 JB 家的 [Remote Development](https://www.jetbrains.com/remote-development/)、或者 vscode 的 [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview); 这两个功能/插件将可以完全覆盖这个插件所有的功能了 😂
