### ISSUE TITLE
how to trigger upload

### ISSUE THREAD

**Issue by ProgrammerXia** [allape/Java-IDEAPlugin-XFTP#3]
Since file in Idea is auto saved, how do I upload the modified files to remote host. Do I need to switch to manual save? Currently when I modified a file, it only said to reopen or truncate file content.

**Comment by allape** [comment]
File should be auto-uploaded if the file is opened by double clicking the item in the remote list. `Rsync` can be found in `Settings > Tools > Rsync`.
