### ISSUE TITLE
Support for Rider 2023.2

### ISSUE THREAD

**Issue by 4bdulla** [allape/Java-IDEAPlugin-XFTP#4]
Hi!

Latest version of Rider unfortunately doesn't support this plugin.
![image](https://github.com/allape/Java-IDEAPlugin-XFTP/assets/51510079/95060b5c-a878-43e5-95c9-87e955b8bda9)

Really helpful tool! 
If it is not supported by maintainer, then let me know, I'll do a fork myself :)

**Comment by allape** [comment]
I am working on this 😂, but pull request is alwasy welcome 😊

**Comment by allape** [comment]
https://github.com/allape/Java-IDEAPlugin-XFTP/releases/tag/v0.10.11
This build should work

**Comment by 4bdulla** [comment]
thanks a lot for a quick update! i'm closing the issue
